### ISSUE TITLE
Laravel 8 >php artisan rabbitmq:consume not working

### ISSUE THREAD

**Issue by julien-viard-infomaniak** [vyuldashev/laravel-queue-rabbitmq#363]
- Laravel 8.5
- RabbitMQ 3.8.8
- Package version: 11

**Describe the bug**

The "name" option does not exist.

**Steps To Reproduce**

php artisan rabbitmq:consume

**Current behavior**

\Illuminate\Queue\Console\WorkCommand

**How to fix**

Update signature like \Illuminate\Console\Command:

``` 
   protected $signature = 'rabbitmq:consume
                            {connection? : The name of the queue connection to work}
                            {--name=default : The name of the worker}
                            {--queue= : The names of the queues to work}
                            {--once : Only process the next job on the queue}
                            {--stop-when-empty : Stop when the queue is empty}
                            {--delay=0 : The number of seconds to delay failed jobs}
                            {--max-jobs=0 : The number of jobs to process before stopping}
                            {--max-time=0 : The maximum number of seconds the worker should run}
                            {--force : Force the worker to run even in maintenance mode}
                            {--memory=128 : The memory limit in megabytes}
                            {--sleep=3 : Number of seconds to sleep when no job is available}
                            {--timeout=60 : The number of seconds a child process can run}
                            {--tries=1 : Number of times to attempt a job before logging it failed}\';
                           
                            {--consumer-tag}
                            {--prefetch-size=0}
                            {--prefetch-count=1000}
                           ';
```

**Comment by vyuldashev** [comment]
Fixed in 11.0.1

**Comment by julien-viard-infomaniak** [comment]
Still missing params for `php artisan rabbitmq:consume`:

The "max-jobs" option does not exist. 
The "max-time" option does not exist.

**Comment by vyuldashev** [comment]
@julien-viard-infomaniak Try v11.0.2 please
